---
apiVersion: v1
kind: Service
metadata:
  name: apache-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache-test

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: dotnet-test

---
apiVersion: v1
kind: Service
metadata:
  name: maven-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: maven-test

---
apiVersion: v1
kind: Service
metadata:
  name: java-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: java-test
